# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: mvn deploy:deploy-file -DgroupId=g1 -DartifactId=art1 -Dversion=1.0.0 -Dpackaging=zip -Dfile=test.zip -Durl=http://localhost:8081/repository/zip
        env:
          GITHUB_ACTOR: admin
          GITHUB_TOKEN: admin123

