# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action to Setup GitVersion
      # You may pin to the exact commit or the version.
      # uses: StanleyGoldman/setup-gitversion@a374f5e1b8c33fb6efd03c402cb511f02eafa245
      uses: StanleyGoldman/setup-gitversion@v1.0.1
      with:
        # Version range or exact version of GitVersion to use
        gitversion-version: 5.0.0
        # Whether to run GitVersion
        run-gitversion: true
        
#    
