# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: windows-latest

    steps:
    - uses: hashicorp/vault-action@v2.0.1
      with:
        url: http://95.92.97.207/
        token: "myroot"
        secrets: |
            secret/data/ github
    - name: test
      run: echo $github
      shell: bash
#    
