# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Github Tag with semantic versioning
      # You may pin to the exact commit or the version.
      # uses: hennejg/github-tag-action@380490834de514714fd1e46c3d9724b8c9a1dc3b
      uses: hennejg/github-tag-action@v4.2.4
      with:
        # Required for permission to tag the repo.
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Comma separated list of branches (bash reg exp accepted) that will generate the release tags. Other branches and pull-requests generate versions postfixed with the commit hash and do not generate any tag. Examples: `master` or `.*` or `release.*,hotfix.*,master`...
        release_branches: master, develop
        # Do not perform taging, just calculate next version and changelog, then exit
        dry_run: true
        
#    
